version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_db_name
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build: ./api
    environment:
      DATABASE_URL: postgres://your_user:your_password@db:5432/your_db_name
    depends_on:
      - db
    ports:
      - "3000:3000"

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - api

  crawler_councilor:
    build: ./crawlers/councilorDataJob
    volumes:
      - ./crawlers/councilorDataJob/output:/app/output
    command: npm start
    depends_on:
      - api

  crawler_frequency:
    build: ./crawlers/frequencyDataJob
    volumes:
      - ./crawlers/frequencyDataJob/output:/app/output
    command: npm start
    depends_on:
      - api

  service_uploader:
    build: ./services/jsonUploader
    volumes:
      - ./services/jsonUploader/input:/app/input
    depends_on:
      - api

volumes:
  db_data: